{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renovate.fullname" . }}-secret
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := index .Values.secrets }}
  {{ $k }}: {{- $v | b64enc | nindent 2 }}
  {{- end }}
  {{- end }}
